---
title: "Meta-Analysis Plot"
author: "Angelika Stefan"
date: "2025-05-14"
output: html_document
---

## Load packages

```{r setup}
library(ggplot2)
library(brms)
library(ggdist)
library(tidybayes)
library(dplyr)
library(stringr)
library(ggtext)
```

## Read in model file

```{r}
meta_results <- readRDS('./model-fits/Meta/bayesMeta1.rds')
```

## Prepare data

```{r}
conditioneffects <- spread_draws(meta_results, r_group[group, term], b_Intercept)
conditioneffects$b_Intercept <- conditioneffects$r_group + conditioneffects$b_Intercept
colnames(conditioneffects)[1] <- "study"
conditioneffects <- conditioneffects[!conditioneffects$study %in% c("Prolific", "MTurk"), ]
```

```{r}
studyeffects <- spread_draws(meta_results, r_study[study, term], b_Intercept)
studyeffects$b_Intercept <- studyeffects$r_study + studyeffects$b_Intercept
```


```{r}
fixedeffect <- spread_draws(meta_results, b_Intercept)
fixedeffect$study <- "Average"
```


```{r}
studyeffects <- rbind(conditioneffects, studyeffects, fixedeffect)
studyeffects <- ungroup(studyeffects)

studyeffects$code <- dplyr::case_match(studyeffects$study,
                                       "1a" ~ "1a_S",
                                       "1b" ~ "1b_S",
                                       c("random", "attitude", "volitional") ~ "2_C",
                                       "2" ~ "2_S",
                                       c("competitive","cooperative", "no_interaction") ~ "3_C",
                                       "3" ~ "3_S",
                                       "Average" ~ "all")
studyeffects$study <- factor(studyeffects$study, 
                             levels = rev(c("1a", "1b", "2", "random", "volitional", "attitude", "3", "no_interaction", "competitive", "cooperative", "Average")),
                             labels = rev(c("<b>Study 1a (Prolific)</b>", "<b>Study 1b (MTurk)</b>", "<b>Study 2</b>", "Condition: Random", "Conditon: Volitional", "Condition: Attitude", "<b>Study 3</b>", "Condition: No Interaction", "Condition: Competitive", "Condition: Cooperative", "<b>Global Effect</b>")))
```


```{r}
summaryStatsStudy <- studyeffects %>% group_by(study) %>% mean_qi(b_Intercept) %>% mutate_if(is.numeric, round, 2)
summaryStatsStudy <- summaryStatsStudy[11:1,]
```

## Plot

```{r}
p <- ggplot(studyeffects, aes(x = b_Intercept, y = study, fill = code)) +
  geom_vline(xintercept = 0, linewidth = 0.25, lty = 2) +
  stat_halfeye(.width = c(.9, .95)) +
scale_fill_manual(values = c("#56B4E9", "#E69F00", "#98E4CF", "#009E73", "#F4B7DA", "#CC79A7", "#6F6E6E"))



p + 
  theme_minimal() +
  labs(
    x = "\nIdeological Asymmetry Effect (Fisher's z)",
    y = "",
    fill = ""
  ) +
  theme(text=element_text(size=20),
        legend.position = "none",
        axis.text.y = element_markdown(size = 16,
                                       angle = 0,
                                       hjust = 1,
                                       vjust=-0.7)) + 
  xlim(-0.3, 0.75) +
  geom_text(
    data = summaryStatsStudy,
    aes(label = str_glue("{b_Intercept} [{.lower}, {.upper}]"), x = 0.75, y=study),
    hjust = "inward", inherit.aes = FALSE, vjust=-1
  )


ggsave("./model-fits/nhbMeta_minimeta-forest.pdf", device = "pdf", width=9.697917, height=6.666667)
ggsave("./model-fits/nhbMeta_minimeta-forest.jpg", device = "jpeg", width=9.697917, height=6.666667)
```


