---
title: "NHB1 Plot"
author: "Youssef Amin and Angelika Stefan"
date: "2025-05-06"
output: html_document
---

## Load packages

```{r setup, include=FALSE}
library(ggplot2)
library(brms)
library(ggside)
```

## Read in data

```{r}
# Read in data
nhb1a <- read.csv('../../data/nhb1a_processed.csv')
nhb1b <- read.csv('../../data/nhb1b_processed.csv')

nhb1a$platform <- "Prolific"
nhb1b$platform <- "MTurk"

# Combine data
nhb1 <- rbind(nhb1a, nhb1b)

# Compute standardized scores for composite political orientation in the combined dataset
nhb1$z_mean_SECS <- scale(nhb1$mean_SECS)
nhb1$z_EconOrient <- scale(nhb1$EconOrient)
nhb1$z_SocOrient <- scale(nhb1$SocOrient)
nhb1$z_PolOrient <- scale(nhb1$PolOrient)
nhb1$composite_political_orientation <- rowMeans(nhb1[, c("z_mean_SECS", "z_EconOrient", "z_SocOrient", "z_PolOrient")], na.rm = TRUE)
nhb1$composite_political_orientation_z <- scale(nhb1$composite_political_orientation)

# Compute standardized scores for mean intergroup bias in the combined dataset
nhb1$z_total_ingroup_minus_outgroup_points <- scale(nhb1$total_ingroup_minus_outgroup_points)
nhb1$z_ingroup_minus_outgroup_traits_positive <- scale(nhb1$ingroup_minus_outgroup_traits_positive)
nhb1$z_ingroup_minus_outgroup_identify <- scale(nhb1$ingroup_minus_outgroup_identify)
nhb1$mean_intergroup_bias <- rowMeans(nhb1[, c("z_total_ingroup_minus_outgroup_points", "z_ingroup_minus_outgroup_traits_positive", "z_ingroup_minus_outgroup_identify")], na.rm = TRUE)
nhb1$mean_intergroup_bias_z <- scale(nhb1$mean_intergroup_bias)

# Read in data from Bayesian models
confirmatory1_bayes <- readRDS("./model-fits/nhb1/confirmatory1_bayesmodel.rds")
confirmatory2_bayes <- readRDS("./model-fits/nhb1/confirmatory2_bayesmodel.rds")
```

## Extract relevant coefficients

```{r}
beta_both <- fixef(confirmatory1_bayes)[2, "Estimate"]
beta_Prolific <- mean(as_draws_array(confirmatory2_bayes, variable="b_composite_political_orientation_z") + as_draws_array(confirmatory2_bayes, variable="b_composite_political_orientation_z:platformProlific"))
beta_MTurk <- fixef(confirmatory2_bayes)[2, "Estimate"]

intercept_both <- fixef(confirmatory1_bayes)[1, "Estimate"]
intercept_Prolific <- mean(as_draws_array(confirmatory2_bayes, variable="b_Intercept") + as_draws_array(confirmatory2_bayes, variable="b_platformProlific"))
intercept_MTurk <- fixef(confirmatory2_bayes)[1, "Estimate"]
```


```{r}
middleplot <- ggplot(nhb1, aes(x = composite_political_orientation_z, 
                 y = mean_intergroup_bias_z,
                 color = platform)) +
  geom_point(alpha = 0.5, size = 2) +  # Scatter points
  geom_abline(slope = beta_both, intercept = intercept_both, linewidth=1.5) +
  geom_abline(slope = beta_Prolific, intercept = intercept_Prolific, color = "#56B4E9", linewidth=1.5) +
  geom_abline(slope = beta_MTurk, intercept = intercept_MTurk, color = "#E69F00", linewidth=1.5) +
  theme_minimal() +
  theme(text=element_text(size=20)) +
  scale_color_manual(values = c("#E69F00", "#56B4E9")) +
  labs(
    color = "Platform",
    x = "Ideology (z-scored)",
    y = "Intergroup Bias (z-scored)"
  ) 

middleplot +
  geom_xsidedensity(aes(y = after_stat(density), xfill = platform), alpha=0.4, linewidth = 1.5) +
  geom_ysidedensity(aes(x = after_stat(density), yfill = platform), alpha=0.4, linewidth = 1.5) +
  scale_xfill_manual(values = c("#E69F00", "#56B4E9")) +
  scale_yfill_manual(values = c("#E69F00", "#56B4E9")) +
  guides(xfill = "none", yfill = "none") +
  scale_ysidex_continuous(guide = "none") +
  scale_xsidey_continuous(guide = "none")

ggsave("./model-fits/nhb1_scatterplot_withDensity.pdf", device = "pdf", width=10.4375, height=8.729167)
ggsave("./model-fits/nhb1_scatterplot_withDensity.jpg", device = "jpeg", width=10.4375, height=8.729167)

```


